import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Helmet } from "react-helmet";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface LayoutProps {
  children: React.ReactNode;
  title?: string;
  description?: string;
  keywords?: string;
  ogImage?: string;
}

export default function Layout({ 
  children, 
  title = "Alex Johnson - Full Stack Developer & UI/UX Enthusiast",
  description = "I craft digital experiences that blend beautiful design with powerful functionality. Passionate about creating scalable solutions that make a difference.",
  keywords = "full stack developer, react developer, ui/ux designer, web developer, javascript, typescript, node.js, portfolio",
  ogImage = "/og-image.jpg"
}: LayoutProps) {
  return (
    <html>
      <body>
    <>
      <Helmet>
        {/* Basic Meta Tags */}
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="keywords" content={keywords} />
        <meta name="author" content="Alex Johnson" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        {/* Open Graph Meta Tags */}
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={ogImage} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Alex Johnson Portfolio" />
        <meta property="og:locale" content="en_US" />
        
        {/* Twitter Card Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={ogImage} />
        <meta name="twitter:creator" content="@alexjohnson" />
        
        {/* Additional Meta Tags */}
        <meta name="robots" content="index, follow" />
        <meta name="theme-color" content="#3B82F6" />
        <meta name="msapplication-TileColor" content="#3B82F6" />
        
        {/* Favicon */}
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        
        {/* Preconnect to Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* Google Fonts */}
        <link 
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" 
          rel="stylesheet" 
        />
        
        {/* JSON-LD Structured Data */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Person",
            "name": "Alex Johnson",
            "jobTitle": "Full Stack Developer",
            "description": "Full Stack Developer & UI/UX Enthusiast specializing in React, Node.js, and modern web technologies",
            "url": "https://alexjohnson.dev",
            "sameAs": [
              "https://github.com/alexjohnson",
              "https://linkedin.com/in/alexjohnson",
              "https://twitter.com/alexjohnson"
            ],
            "knowsAbout": [
              "React",
              "TypeScript",
              "Node.js",
              "Python",
              "GraphQL",
              "AWS",
              "UI/UX Design",
              "Web Development"
            ]
          })}
        </script>
      </Helmet>
      
      {/* Main Content */}
      <div className="font-inter antialiased">
        {children}
      </div>
    </>
    </body>
    </html>
  );
}
